---
- name: Converge
  hosts: all
  become: true
  vars:
    local_role_name: "ansible-role-docker-login"
    role_name: "{% if lookup('env','ROLE_NAME_FULL') %}{{ lookup('env','ROLE_NAME_FULL') }}{% else %}{{ local_role_name }}{% endif %}"

  roles:
    - {
      role: "{{ role_name }}",
      debug_hide: false
    }
